version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - npm install -g yarn
      - yarn install
  pre_build:
    commands:
      - yarn test
      - echo "Creating .env file"
      - echo "BRANCH_NAME=$BRANCH_NAME\nMONGO_USERNAME=$MONGO_USERNAME\nMONGO_PASSWORD=$MONGO_PASSWORD" > .env
  build:
    commands:
      - echo Starting Deployment
      - yarn deploy --stage $STAGE
  post_build:
    commands:
      - echo Build Completed on `date`
