export const templateResolvers = {
  'Query  getTemplates': 'templateLambda',
  'Query  getMenuTemplates': 'templateLambda',
  'Query  getPages': 'templateLambda',
  'Query  getTemplate': 'templateLambda',
  'Query  getPage': 'templateLambda',
  'Query  getTemplateBySlug': 'templateLambda',
  'Query  getPageBySlug': 'templateLambda',
  'Query  getPageMentions': 'templateLambda',
  'Query  getMentionItems': 'templateLambda',
  'Mutation createTemplate': 'templateLambda',
  'Mutation createPage': 'templateLambda',
  'Mutation updatePage': 'templateLambda',
  'Mutation updateTemplate': 'templateLambda',
  'Mutation deletePage': 'templateLambda',
  'Mutation deleteTemplate': 'templateLambda',
};
