export const templateResolvers = {
  'Query  getTemplates': 'templateLambda',
  'Query  getMenuTemplates': 'templateLambda',
  'Query  getTemplateInstances': 'templateLambda',
  'Query  getTemplate': 'templateLambda',
  'Query  getTemplateInstance': 'templateLambda',
  'Query  getTemplateBySlug': 'templateLambda',
  'Query  getTemplateInstanceBySlug': 'templateLambda',
  'Query  getTemplateInstanceMentions': 'templateLambda',
  'Query  getMentionItems': 'templateLambda',
  'Mutation createTemplate': 'templateLambda',
  'Mutation createTemplateInstance': 'templateLambda',
  'Mutation updateTemplateInstance': 'templateLambda',
  'Mutation updateTemplate': 'templateLambda',
  'Mutation deleteTemplateInstance': 'templateLambda',
  'Mutation deleteTemplate': 'templateLambda',
};
