export const formResolvers = {
  'Query getForm': 'formLambda',
  'Query getFormBySlug': 'formLambda',
  'Query getForms': 'formLambda',
  'Mutation createForm': 'formLambda',
  'Mutation updateForm': 'formLambda',
  'Mutation deleteForm': 'formLambda',
  'Query getResponse': 'formLambda',
  'Query getResponseByCount': 'formLambda',
  'Query getResponses': 'formLambda',
  'Mutation createResponse': 'formLambda',
  'Mutation updateResponse': 'formLambda',
  'Mutation deleteResponse': 'formLambda',
  'Query getMyResponses': 'formLambda',
  'Mutation createBulkResponses': 'formLambda',
  'Query getSection': 'formLambda',
  'Mutation updateSection': 'formLambda',
};
