export const listResolvers = {
  "Query  getListTypes": "listLambda",
  "Query  getListItems": "listLambda",
  "Query  getListType": "listLambda",
  "Query  getListItem": "listLambda",
  "Query  getListTypeBySlug": "listLambda",
  "Query  getListItemBySlug": "listLambda",
  "Mutation createListType": "listLambda",
  "Mutation createListItem": "listLambda",
  "Mutation updateListItem": "listLambda",
  "Mutation updatePublish": "listLambda",
  "Mutation updateListType": "listLambda",
  "Mutation deleteListItem": "listLambda",
  "Mutation deleteListType": "listLambda",
};
