export const listResolvers = {
  'Query  getListTypes': 'listLambda',
  'Query  getMenuListTypes': 'listLambda',
  'Query  getListItems': 'listLambda',
  'Query  getListType': 'listLambda',
  'Query  getListItem': 'listLambda',
  'Query  getListTypeBySlug': 'listLambda',
  'Query  getListItemBySlug': 'listLambda',
  'Query  getListPageMentions': 'listLambda',
  'Mutation createListType': 'listLambda',
  'Mutation createListItem': 'listLambda',
  'Mutation updateListItem': 'listLambda',
  'Mutation updateListType': 'listLambda',
  'Mutation deleteListItem': 'listLambda',
  'Mutation deleteListType': 'listLambda',
};
